version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/brute-force-demo/public
      - ./config:/var/www/brute-force-demo/config
      - ./includes:/var/www/brute-force-demo/includes
      - ./data:/var/www/brute-force-demo/data
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=127.0.0.1
      - PHP_FPM_SERVER_PORT=9000
    restart: unless-stopped 