services:
  web:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/brute-force-demo/public:ro
      - ./config:/var/www/brute-force-demo/config:ro
      - ./includes:/var/www/brute-force-demo/includes:ro
      - ./data:/var/www/brute-force-demo/data:ro
      - runtime_data:/var/run
      - nginx_logs:/var/log/nginx
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=127.0.0.1
      - PHP_FPM_SERVER_PORT=9000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  runtime_data:
  nginx_logs: