services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-login-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: always
